services:
  - type: web
    name: my-mern-backend
    env: node
    region: oregon
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
